# Generated by Django 3.2.6 on 2023-02-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.FileField(blank=True, null=True, upload_to='post'),
        ),
    ]
