# Generated by Django 3.2.6 on 2023-02-10 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20230210_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_replays', to=settings.AUTH_USER_MODEL, verbose_name='replied by'),
        ),
    ]
